"""Write out/ENGINE_NOTES.md from the files the engine produced. No number is typed by hand."""
import json
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import engine_prep as ep  # noqa: E402

OUT = ep.OUT


def J(path):
    with open(os.path.join(OUT, path)) as f:
        return json.load(f)


def main(cases):
    # §3.4 output missing for a case (the overload stage was never run): build it from the saved flows first.
    for c in cases:
        if not os.path.exists(os.path.join(OUT, f"{c}_overload_stats.json")):
            print(f"[{c}] overload_stats.json missing -> running engine_prep.overload_series")
            ep.overload_series(c)
    L = []
    L.append("# ENGINE_NOTES — MASTER §2 and §3 for all cases\n")
    L.append("Generated by `src/engine_notes.py` from the files under `out/`; every number below is read from those files.\n")
    L.append("Code: `src/engine_prep.py` (prepare, classify_group, run_baseline, compute_ptdf_lodf, overload_series, "
             "verify_lodf_dcpf), driver `src/run_engine.py <case> [baseline|ptdf|overload|verify|notes|all]`, "
             "sequential baseline chain `src/run_baselines.sh`.\n")
    L.append("Tie: line `3581-89516-1` replaced by Link `LKY-STRABANE-PST` (p_nom = removed s_nom). Contingency `2522-5042-1`. "
             "Monitored rows: FLG_SLIGO_N1 = `2521-4981-1` post-contingency, T25221_N1 = `T2522-2521-25221-1-w1` post-contingency, "
             "T25222_N1 = `T2522-2521-25222-2-w1` post-contingency, FLG_SLIGO_N0 = `2521-4981-1` intact.\n")

    # ---- §2 classification
    L.append("## §2 Group definition and classification (`out/<case>_group_units.csv`)\n")
    rows = []
    for c in cases:
        s = J(f"{c}_group_stats.json")
        rows.append(dict(case=c, units=s["n_units"], matched=s["n_matched"], match_rate=f"{100*s['match_rate']:.1f}%",
                         unmatched=s["n_unmatched"], multi=s["n_multi"], P=s["n_P"], N=s["n_N"], U=s["n_U"],
                         MW_total=f"{s['mw_total']:.1f}", MW_G=f"{s['mw_G']:.1f}", MW_excluded_U=f"{s['mw_excluded_U']:.1f}",
                         MW_P=f"{s['mw_P']:.1f}", MW_N=f"{s['mw_N']:.1f}"))
    L.append(pd.DataFrame(rows).to_markdown(index=False) + "\n")
    L.append("Unmatched units default to class P per §2.1 (flagged `unmatched`). Bus numbers of the CG3 stations are identical "
             "in WP2024 wind-in and WP2033 (`bus_differs` false for all 16 buses; printed by classify_group).\n")
    for c in cases:
        u = pd.read_csv(os.path.join(OUT, f"{c}_group_units.csv"))
        um = u[u.match_status == "unmatched"]
        L.append(f"Unmatched in {c} ({len(um)}): " + ", ".join(f"{r.generator} {r.psse_bus_name} {r.p_nom:.3g} MW @{r.station}" for r in um.itertuples()) + "\n")

    # ---- §3.1 prepare / §3.2 baseline
    L.append("## §3.1–3.2 Preparation and baseline (`out/<case>_baseline_sanity.json`, `_chunk_status.csv`, `_profile_borrowing.csv`)\n")
    rows = []
    for c in cases:
        s = J(f"{c}_baseline_sanity.json")
        st = pd.read_csv(os.path.join(OUT, f"{c}_chunk_status.csv"))
        rows.append(dict(case=c, hours=s["hours"], step=s["step"], chunks=len(st),
                         chunks_optimal=int(((st.condition == "optimal") & (st.status == "ok")).sum()),
                         year_cols=f"{s['year_cols_matching']}/{s['year_cols_total']}",
                         borrowed_profiles=s["borrowed"], borrowed_MW=f"{s['borrowed_mw']:.0f}",
                         thermal_no_col=s["thermal_without_column"], p_min_pu_clipped=s["p_min_pu_clipped"],
                         tie_p_nom=s["tie_p_nom"], solve_min=f"{s['solve_seconds']/60:.0f}"))
    L.append(pd.DataFrame(rows).to_markdown(index=False) + "\n")
    L.append("(a) Every chunk optimal: " + ", ".join(f"{c}: {J(f'{c}_baseline_sanity.json')['all_chunks_optimal']}" for c in cases) + "\n")
    L.append("### (f) Baseline sanity\n")
    rows = []
    for c in cases:
        s = J(f"{c}_baseline_sanity.json")
        rows.append(dict(case=c, wind_surplus_share=f"{100*s['wind_surplus_share']:.2f}%",
                         wind_solar_surplus_share=f"{100*s['ws_surplus_share']:.2f}%",
                         G_surplus_share=f"{100*s['G_surplus_share']:.2f}%",
                         load_shedding_hours=s["load_shedding_hours"], load_shedding_MWh=f"{s['load_shedding_MWh']:.1f}",
                         tie_at_cap_share=f"{100*s['tie_at_cap_share']:.1f}%", tie_at_cap_hours=s["tie_at_cap_hours"],
                         tie_mean_MW=f"{s['tie_mean_flow_MW']:.1f}"))
    L.append(pd.DataFrame(rows).to_markdown(index=False) + "\n")
    L.append("Surplus share = 1 − dispatched / available (island, unconstrained dispatch, ratings ×100): what the LOPF withholds "
             "for lack of demand or export, not a network constraint. Tie sign: positive = 3581 (Letterkenny) → 89516 (Strabane).\n")

    # ---- §3.3
    L.append("## §3.3 PTDF, LODF, shift factors (`out/<case>_lodf.csv`, `_reference_bus.csv`, `_shift_factors.csv`, `_node_table.csv`, `_ptdf_summary.json`)\n")
    L.append("### (c) Reference bus\n")
    rows = []
    for c in cases:
        s = J(f"{c}_ptdf_summary.json")
        r = dict(case=c, ref_bus=s["ref_bus"], ref_name=s["ref_name"])
        for e, v in s["P_e_ref"].items():
            r[f"|P[{e},ref]|"] = f"{abs(v):.5f}"
        for m, v in s["Pk_m_ref"].items():
            r[f"|Pk[{m},ref]|"] = f"{abs(v):.5f}"
        rows.append(r)
    L.append(pd.DataFrame(rows).to_markdown(index=False) + "\n")
    L.append("Rule: bus of the largest-p_nom generator with carrier `gas`; accepted if |P[e,ref]| < 0.02 on every monitored element "
             "(first candidate accepted in every case; see `_reference_bus.csv`).\n")
    L.append("### (b) LODF for contingency `2522-5042-1` vs PyPSA `SubNetwork.calculate_BODF`\n")
    for c in cases:
        d = pd.read_csv(os.path.join(OUT, f"{c}_lodf.csv"))
        L.append(f"**{c}**\n\n" + d[["element", "lodf_kit", "bodf_pypsa", "abs_diff", "agree_1e6", "denom"]].to_markdown(index=False, floatfmt=".9g") + "\n")
        p = os.path.join(OUT, f"{c}_lodf_dcpf_check.csv")
        if os.path.exists(p):
            d2 = pd.read_csv(p)
            L.append(f"Independent check, {c}: contingency line removed and DC flows rebuilt from the frozen baseline injections "
                     f"(`flowmath.flows`) on {d2.hour.nunique()} hours: max |LOPF − DC| intact {d2.intact_diff.abs().max():.2e} MW, "
                     f"max |(f_e + LODF·f_k) − DC post-contingency| {d2.post_diff.abs().max():.2e} MW (`{c}_lodf_dcpf_check.csv`).\n")
    L.append("### (d) WDT-style node table, SF on the Flagford–Sligo N-1 row (`out/<case>_node_table.csv`)\n")
    for c in cases:
        s = J(f"{c}_ptdf_summary.json")
        t = pd.read_csv(os.path.join(OUT, f"{c}_node_table.csv"))
        top = t[t.SF_FLG_SLIGO_N1 >= ep.SF_FLOOR].copy()
        cols = ["bus", "psse_name", "station", "in_CG3", "ws_p_nom", "SF_FLG_SLIGO_N1", "SF_T25221_N1", "SF_T25222_N1", "SF_FLG_SLIGO_N0", "ratio_to_next", "step_change"]
        L.append(f"**{c}** — rows oriented so the group's mean SF is positive (orientation {s['orientation']}); nodes with SF ≥ {ep.SF_FLOOR} shown ({len(top)} of {s['n_nodes']} wind/solar nodes on the island).\n")
        L.append(top[cols].to_markdown(index=False, floatfmt=".4f") + "\n")
        L.append(f"Step change: largest ratio {s['step_ratio']:.3f} between rank {s['step_rank']} ({s['step_after_name']}, {s['step_value_above']:.4f}) "
                 f"and the next ({s['step_value_below']:.4f}). CG3 nodes occupy ranks {s['cg3_rank_range'][0]}–{s['cg3_rank_range'][1]} "
                 f"(SF {s['cg3_SF_min']:.4f}–{s['cg3_SF_max']:.4f}). CG3 nodes below the step: {s['cg3_nodes_below_step'] or 'none'}. "
                 f"Non-CG3 nodes above the step: {s['non_cg3_nodes_above_step'] or 'none'}.\n")

    # ---- §3.4
    L.append("## §3.4 Overload series (`out/<case>_overloads.csv`, `_overload_stats.json`)\n")
    L.append("### (e) Overload statistics\n")
    rows = []
    for c in cases:
        s = J(f"{c}_overload_stats.json")
        r = dict(case=c, hours=s["hours"], step=s["step"], hours_any=s["hours_any_overload"],
                 share_any=f"{100*s['share_hours_any_overload']:.2f}%", total_MWh=f"{s['total_overload_MWh_all_rows']:.0f}",
                 max_MW=f"{s['max_overload_MW']:.1f}", max_row=s["max_overload_row"],
                 multi_row_share=("n/a" if s["share_overload_hours_multi_row"] != s["share_overload_hours_multi_row"] else f"{100*s['share_overload_hours_multi_row']:.1f}%"))
        rows.append(r)
    L.append(pd.DataFrame(rows).to_markdown(index=False) + "\n")
    rows = []
    for c in cases:
        s = J(f"{c}_overload_stats.json")
        for m in ep.MONITORED:
            rows.append(dict(case=c, row=m, element=ep.MONITORED[m][0], rating=s[f"rating_{m}"], hours_over=s[f"hours_over_{m}"],
                             overload_MWh=f"{s[f'overload_MWh_{m}']:.0f}", max_overload_MW=f"{s[f'max_over_{m}']:.1f}",
                             max_abs_flow_MW=f"{s[f'max_abs_flow_{m}']:.1f}",
                             share_over_with_positive_flow=("n/a" if s[f"share_pos_flow_over_{m}"] != s[f"share_pos_flow_over_{m}"] else f"{100*s[f'share_pos_flow_over_{m}']:.1f}%")))
    L.append(pd.DataFrame(rows).to_markdown(index=False) + "\n")
    L.append("Overload MWh = Σ_h O_m,h × step (step = 2 for the WP2033 cases). `share_over_with_positive_flow` says which direction "
             "overloads (positive p0 = bus0→bus1: Flagford→Sligo for the line, star point→220 kV bus for the transformer windings).\n")

    # ---- files
    L.append("## Files written\n")
    for c in cases:
        fs = sorted(f for f in os.listdir(OUT) if f.startswith(c) and not f.startswith("_"))
        L.append(f"**{c}**: " + ", ".join(f"`out/{f}`" for f in fs) + "\n")
    L.append("Shared: `out/DECISIONS_LOG.md` ([engine] lines), `out/ENGINE_NOTES.md`, `out/logs/`.\n")
    with open(os.path.join(OUT, "ENGINE_NOTES.md"), "w") as f:
        f.write("\n".join(L))
    print("wrote out/ENGINE_NOTES.md")


if __name__ == "__main__":
    main(sys.argv[1:] or list(ep.CASES))
