"""WP-H - the consultation-shaped evidence pack (design brief v2, WP-H).

Sized as a consultation response, not a paper: problem statement, measurement,
method, options, legal analysis, implementation cost, open questions. It names
the decision that would be required and the modification route.

Every figure is read from a file in out/ and the file is named beside it, per
the project's working agreement. Claims whose inputs are still open in the
brief's verification queue are marked, not filled.

    python project/src/wp_h_pack.py    ->  out/EVIDENCE_PACK.md
"""
from __future__ import annotations

import json

import numpy as np
import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "out"


def read_json(name):
    p = OUT / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def read_csv(name):
    p = OUT / name
    return pd.read_csv(p) if p.exists() else None


def main() -> int:
    wpa = read_json("wpa_summary.json")
    wpe = read_csv("wpe_bound.csv")
    wpes = read_json("wpe_summary.json")
    wpc = read_json("wpc_summary.json")
    asrt = read_csv("wpa_assertions.csv")
    meas_g = read_csv("measurement_groups.csv")
    summ = read_csv("WP2024s42_summary.csv")

    b3 = wpe[wpe.band_pp == 3.0].iloc[0]
    b0 = wpe[wpe.band_pp == 0.0].iloc[0]
    obs_div = wpes["observed_pro_rata_max_divergence_pp"]

    L = [
        "# Evidence pack: the intra-group allocation rule for wind constraint",
        "",
        "Shaped as a consultation response, not a paper. Generated by",
        "`src/wp_h_pack.py`; every number is read from a named file in `out/`.",
        "",
        "---",
        "",
        "## 1. The question put",
        "",
        "When EirGrid's Wind Dispatch Tool constrains a North-West group, it issues",
        "**one** joint MW instruction and splits it **pro rata on availability**.",
        "The shift factor - each farm's MW of flow relief per MW cut - is used to",
        "*build* the group and is then discarded at the split.",
        "",
        "The question is narrow and is for the regulator, not for us: **does the",
        "duty to minimise renewable redispatch bear on the choice of intra-group",
        "allocation rule?** Nothing here asks for new groups, new payments, or a",
        "new tool. Same groups, same tool, one formula changed.",
        "",
        "## 2. What pro rata actually delivered (measured)",
        "",
    ]

    if meas_g is not None:
        cg3 = meas_g[(meas_g.group == "CG3") & (meas_g.level == "unit")]
        cg1 = meas_g[(meas_g.group == "CG1") & (meas_g.level == "unit")]
        if len(cg3) and len(cg1):
            r3, r1 = cg3.iloc[0], cg1.iloc[0]
            L += [
                "From SEM-O dispatch data over summer 2026 "
                "(`out/measurement_groups.csv`):",
                "",
                f"- North-West Group 3, {int(r3.N)} units: constraint-only share of",
                f"  available energy runs {100 * r3['min']:.1f} % to {100 * r3['max']:.1f} %",
                f"  ({r3.max_over_min:.2f}x), Gini {r3.gini:.3f}.",
                f"- Group 1, {int(r1.N)} units: {100 * r1['min']:.1f} % to "
                f"{100 * r1['max']:.1f} % ({r1.max_over_min:.2f}x), Gini {r1.gini:.3f}.",
                "",
                "Equal treatment at the instant of the instruction does not produce",
                "equal outcomes over a season. That is the starting fact.",
                "",
            ]

    L += [
        "## 3. What it cost (measured, no weather model)",
        "",
        "The equal-relief replay takes every half-hour in which a North-West unit",
        "was actually under constraint, computes the flow relief the observed cut",
        "delivered, and asks what the cheapest cut delivering **the same relief**",
        "would have been. Source `out/wpa_summary.json`.",
        "",
        f"- Window {wpa['window'][0]} to {wpa['window'][1]}, "
        f"{wpa['half_hours_with_relief']} half-hours, {wpa['units']} units.",
        f"- Observed cut **{wpa['observed_cut_MWh']:,.0f} MWh**.",
        f"- Effectiveness-ordered cut delivering identical relief "
        f"**{wpa['effectiveness_cut_MWh']:,.0f} MWh**.",
        f"- **Excess spill under pro rata: {wpa['effectiveness_saving_MWh']:,.0f} MWh, "
        f"{wpa['effectiveness_saving_pct']:.2f} %.**",
        "",
        "This uses real instructions and real availability. No synthetic weather",
        "enters it. The counterfactual is constrained to the same relief, so it is",
        "not a security trade.",
        "",
        "## 4. Security is not traded",
        "",
    ]
    if asrt is not None:
        a1 = asrt[asrt.assertion.str.startswith("A1")]
        detail = a1.detail.iloc[0] if len(a1) else "n/a"
        L += [
            f"Every rule delivers the observed relief exactly ({detail}, "
            "`out/wpa_assertions.csv`).",
            "Grid stability does not consider economics, and nothing here asks it to:",
            "efficiency and equity operate only inside the security-feasible set.",
            "",
        ]

    L += [
        "## 5. The proposed rule, and what it guarantees",
        "",
        "Effectiveness order, applied only among farms whose **year-to-date** cut",
        "ratio is within `b` percentage points of the group average. `b = 0`",
        "reproduces today; `b = infinity` is pure effectiveness. The ledger is in",
        "MWh ratio, not euro, so it is invariant to whatever the compensation",
        "regime turns out to be after C-36/25.",
        "",
        "Source `out/wpe_bound.csv`:",
        "",
        "| | today (b=0) | b = 3 pp | pure effectiveness |",
        "|---|---|---|---|",
        f"| spill saved vs observed | {wpa['band0pp_saving_pct']:.2f} % | "
        f"{wpa['band3pp_saving_pct']:.2f} % | {wpa['effectiveness_saving_pct']:.2f} % |",
        f"| **guaranteed** divergence bound | {b0.claimed_bound_pp:.2f} pp | "
        f"{b3.claimed_bound_pp:.2f} pp | none |",
        f"| realised divergence | {b0.realised_max_divergence_pp:.2f} pp | "
        f"{b3.realised_max_divergence_pp:.2f} pp | "
        f"{wpe[np.isinf(wpe.band_pp)].realised_max_divergence_pp.iloc[0]:.2f} pp |",
        f"| feasibility escapes | {int(b0.feasibility_escapes)} | "
        f"{int(b3.feasibility_escapes)} | 0 |",
        "",
        "**The asymmetry is the point.** Pro rata bounds nothing. Its equality is",
        "asserted at the instant of application; over this window it realised",
        f"**{obs_div:.2f} pp** of divergence between the worst-hit unit and the group",
        f"mean. The band rule at b = 3 offers an ex-ante guarantee of "
        f"{b3.claimed_bound_pp:.2f} pp,",
        "provable in advance and testable after the fact. A court can check a bound;",
        "it cannot check an intention.",
        "",
        "State honestly which comparison is which:",
        "",
        f"- model against model, b = 3 costs "
        f"{b3.realised_max_divergence_pp - b0.realised_max_divergence_pp:.2f} pp of realised",
        f"  equality against b = 0 while saving {wpa['band3pp_saving_pct']:.2f} % of spill;",
        f"- the *guarantee* at b = 3 ({b3.claimed_bound_pp:.2f} pp) is tighter than pro",
        f"  rata's *realised* {obs_div:.2f} pp.",
        "",
        "## 6. What it would cost to run",
        "",
    ]
    if wpc is not None:
        v = wpc["C5_values_pct"]
        L += [
            "One operator action per event, as today. The eligible list is",
            "precomputed and refreshed on a slow cadence, not solved in the control",
            "room. Source `out/wpc_burden.csv`.",
            "",
            f"- k = 2 sub-groups, daily refresh: **{v.get('2', float('nan')):.1f} %** of the",
            "  ideal gain retained.",
            f"- k = 3: {v.get('3', float('nan')):.1f} %.",
            "",
            "The brief's own test for implementability (at least 50 % retained at",
            f"k <= 3, daily) is **{'met' if wpc['C5_holds'] else 'not met'}**: it holds at",
            "k = 2 and fails at k = 3. Reported as failed rather than softened.",
            "",
            "The design choice that matters is how the sub-groups are formed, not how",
            "many there are. Contiguous shift-factor tiers perform badly; an",
            "interleaved split roughly triples retained gain at k = 3.",
            "",
        ]

    L += [
        "## 7. Legal analysis",
        "",
        "**Affirmative**",
        "",
        "1. **Non-discrimination** (Reg. 2019/943 Art. 12(1), 13(1); Electricity",
        "   Regulation Act 1999 s.9(4)(a)). The rule is objective, published, applied",
        "   identically to every unit, and keys only on a technical characteristic",
        "   (shift factor) plus a symmetric equity counter. No unit is treated",
        "   differently by identity, ownership or nationality.",
        "2. **Minimisation of renewable redispatch** (Art. 13(5)(b), 13(6)(a)). Pro",
        "   rata demonstrably cuts more renewable MWh than an available alternative",
        "   delivering identical security. Put as a question to the regulator, not as",
        "   an accusation.",
        "3. **Consumer benefit.** A measure that reduces system balancing costs borne",
        "   by the taxpayer is the durable defence. The MWh difference is measured;",
        "   the euro conversion is **not yet admissible** (section 9).",
        "4. **Ex-ante guarantee.** The band bounds year-end divergence. Pro rata does",
        "   not bound anything.",
        "5. **EirGrid's own rationale supports it.** The step-change threshold that",
        "   builds a group exists so that low-impact farms are not constrained",
        "   inefficiently. The band applies the same logic one level down, inside the",
        "   group.",
        "",
        "**Risks, stated not hidden**",
        "",
        "- **C-36/25 (Energia Group e.a.)**, referred by the Irish Supreme Court on",
        "  21 Jan 2025, asks whether Art. 13(7) requires full indifference",
        "  compensation for firm-access generators. The whole compensation regime is",
        "  interim. The design must work under either outcome: an MWh ledger does, a",
        "  euro-gated ledger would not.",
        "- **SEM-24-044** remains an outstanding decision. Non-priority-first is not",
        "  live and must not be described as live.",
        "- A farm that loses under the change may litigate. The bound, the published",
        "  rule and the consumer-benefit evidence are the answer.",
        "- Change requires consultation and CRU approval. That is a strength of a",
        "  document shaped for that process, not a weakness.",
        "",
        "## 8. The decision and the route",
        "",
        "- **Who decides the weights:** the SEM Committee, CRU or DECC - not the",
        "  analyst. `out/wpg_mcda.md` is the options-by-criteria table with the",
        "  weight column deliberately blank, plus the sweep showing which weight",
        "  vectors select which option.",
        "- **Route:** consultation, then CRU decision, then a Grid Code / TS&C",
        "  modification.",
        "",
        "## 9. What is not yet established",
        "",
        "Nothing in this list may go on a slide until it is sourced.",
        "",
        "1. The implied EUR/MWh from the EUR 34.92 m 2025/26 constrained provision -",
        "   the forecast constrained MWh denominator is not sourced, so no euro",
        "   figure is asserted here. `wpg_mcda.csv` sweeps the rate instead.",
        "2. The marginal emissions factor for displaced generation.",
        "3. Which North-West units are RESS-supported, needed for any Community",
        "   Benefit Fund number.",
        "4. The commissioning-date cut-off used by SDP-01/04 (4 July 2019, or an",
        "   earlier 2018 date).",
        "5. Whether the 26 Nov 2025 rebalancing step is in routine use.",
        "6. WDT group to binding-element mapping completeness.",
        "",
        "## 10. Limits of the evidence",
        "",
        "- One summer, one constraint group, one binding element. Not a year.",
        "- Shift factors come from the 2024 TYTFS network, applied to 2026 operation.",
        "- One contingency where the real tool has many outage variants.",
        "- Availability declarations are taken as honest.",
        "- The synthetic-year results are ratios and ranks only; no absolute energy.",
        "- The SEM-O window can no longer be pulled in full (retention now starts",
        "  2026-06-09 23:00). See `verify/v06_measurement.md`.",
        "",
    ]

    if summ is not None and "D_ratio" in summ.columns:
        r = summ.set_index("rule")
        if "rule2" in r.index:
            L += [
                "## Appendix: the synthetic-year cross-check",
                "",
                "The full-year simulation (`out/WP2024s42_summary.csv`) is a separate,",
                "weaker line of evidence, kept for the frontier shape only:",
                "",
                f"- rule 2 against rule 1: D_ratio {r.loc['rule2', 'D_ratio']:.3f}, i.e. pro",
                f"  rata spills {100 * (1 / r.loc['rule2', 'D_ratio'] - 1):.1f} % more over a",
                "  synthetic year, against the measured "
                f"{wpa['effectiveness_saving_pct']:.2f} % on real data.",
                "- The two agree in direction and differ in size, which is what one",
                "  should expect: the synthetic year has more binding hours and a",
                "  different fleet. Report the measured number as the headline.",
                "",
            ]

    (OUT / "EVIDENCE_PACK.md").write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {OUT / 'EVIDENCE_PACK.md'} ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
